id = "csv"
name = "CSV"
description = "CSV language support."
version = "0.0.2"
schema_version = 1
authors = ["Jason Lee <huacnlee@gmail.com>"]
repository = "https://github.com/huacnlee/zed-csv"

[grammars.csv]
repository = "https://github.com/arnau/tree-sitter-csv"
commit = "4b25b5d745f9462e54b781e3d7798b8e0a4db703"
